version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "bidMessage:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper    

  api_service:
    build: .
    restart: always
    ports:
      - 8081:8080
    links:
      - mongo_db:app_db
    depends_on:
      - zookeeper
      - kafka
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27018:27017